<Window x:Class="DragonQuestinoEditor.CreateTileMapWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:DragonQuestinoEditor"
        mc:Ignorable="d"
        Title="Create New Tile Map"
        Height="150"
        Width="300"
        ResizeMode="NoResize">
   <Grid>
      
      <Grid.ColumnDefinitions>
         <ColumnDefinition Width="100" />
         <ColumnDefinition />
      </Grid.ColumnDefinitions>
      <Grid.RowDefinitions>
         <RowDefinition Height="26" />
         <RowDefinition Height="26" />
         <RowDefinition Height="26" />
         <RowDefinition />
      </Grid.RowDefinitions>

      <!-- Name -->
      <TextBlock Grid.Column="0"
                 Grid.Row="0"
                 HorizontalAlignment="Right"
                 VerticalAlignment="Center"
                 Margin="3"
                 Text="Name:"/>
      <TextBox x:Name="TileMapName"
               Grid.Column="1"
               Grid.Row="0"
               Margin="3"/>

      <!-- Horizontal Tiles -->
      <TextBlock Grid.Column="0"
                 Grid.Row="1"
                 HorizontalAlignment="Right"
                 VerticalAlignment="Center"
                 Margin="3"
                 Text="Horizontal Tiles:"/>
      <TextBox x:Name="HorizontalTilesTextBox"
               Grid.Column="1"
               Grid.Row="1"
               Margin="3"
               PreviewTextInput="TileCount_PreviewTextInput"/>
      
      <!-- Vertical Tiles -->
      <TextBlock Grid.Column="0"
                 Grid.Row="2"
                 HorizontalAlignment="Right"
                 VerticalAlignment="Center"
                 Margin="3"
                 Text="Vertical Tiles:"/>
      <TextBox x:Name="VerticalTilesTextBox"
               Grid.Column="1"
               Grid.Row="2"
               Margin="3"
               PreviewTextInput="TileCount_PreviewTextInput"/>
      
      <!-- Create/Cancel buttons -->
      <StackPanel Grid.Column="0"
                  Grid.Row="3"
                  Grid.ColumnSpan="2"
                  Orientation="Horizontal"
                  HorizontalAlignment="Right"
                  VerticalAlignment="Bottom">
         <Button Margin="6"
                 Content="Create Tile Map"
                 Click="CreateButton_Click"/>
         <Button Margin="6"
                 Content="Cancel"
                 Click="CancelButton_Click"/>
      </StackPanel>

   </Grid>
</Window>
